var constants = {
  //Login

  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',

  //Simulation config

  ADD_SIMUL: 'ADD_SIMUL',
  ADD_SIMUL_SUCCESS: 'ADD_SIMUL_SUCCESS',
  ADD_SIMUL_FAIL: 'ADD_SIMUL_FAIL',


  // Simulation Model Creation
  ADD_SIMUL_ROLE: 'ADD_SIMUL_ROLE',
  ADD_SIMUL_MODEL_RESOURCE: 'ADD_SIMUL_MODEL_RESOURCE',
  ADD_SIMUL_MODEL_ACTION: 'ADD_SIMUL_MODEL_ACTION',
  ADD_SIMUL_MODEL_ACTION_AVAILABLEIF: 'ADD_SIMUL_MODEL_ACTION_AVAILABLEIF',
  ADD_SIMUL_MODEL_ACTION_AVAILABLEFOR: 'ADD_SIMUL_MODEL_ACTION_AVAILABLEFOR',
  ADD_SIMUL_MODEL_ACTION_EFFECT: 'ADD_SIMUL_MODEL_ACTION_EFFECT',
  ADD_SIMUL_MODEL_ACTION_END_OF_ROUND_CONDITION: 'ADD_SIMUL_MODEL_ACTION_END_OF_ROUND_CONDITION',

  // students
  INIT_STUDENTS: 'INIT_STUDENTS',
  REMOVE_STUDENT: 'REMOVE_STUDENT',


  //Simulations
  LOAD_SIMUL: "LOAD_SIMUL",
  LOAD_SIMUL_SUCCESS: "LOAD_SIMUL_SUCCESS",
  LOAD_SIMUL_FAIL: "LOAD_SIMUL_FAIL",

  ADD_SIMUL_FIELD_SUCCESS: "ADD_SIMUL_FIELD_SUCCESS",
  ADD_SIMUL_FIELD_FAIL: "ADD_SIMUL_FIELD_FAIL",

  //Classes

  LOAD_CLASSES: "LOAD_CLASSES",
  LOAD_CLASSES_SUCCESS: "LOAD_CLASSES_SUCCESS",
  LOAD_CLASSES_FAIL: "LOAD_CLASSES_FAIL",

  ADD_CLASSE: "ADD_CLASSE",
  ADD_CLASSE_SUCCESS: "ADD_CLASSE_SUCCESS",
  ADD_CLASSE_FAIL: "ADD_CLASSE_FAIL",

  // Sign up
  ADD_USER: "ADD_USER",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAIL: "ADD_USER_FAIL"
};

module.exports = constants;
