var constants = {
  //Login

  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',

  //Simulation config

  ADD_SIMUL: 'ADD_SIMUL',
  ADD_SIMUL_SUCCESS: 'ADD_SIMUL_SUCCESS',
  ADD_SIMUL_FAIL: 'ADD_SIMUL_FAIL',


  //Simulations
  LOAD_SIMUL: "LOAD_SIMUL",
  LOAD_SIMUL_SUCCESS: "LOAD_SIMUL_SUCCESS",
  LOAD_SIMUL_FAIL: "LOAD_SIMUL_FAIL",

  //Classes

  LOAD_CLASSES: "LOAD_CLASSES",
  LOAD_CLASSES_SUCCESS: "LOAD_CLASSES_SUCCESS",
  LOAD_CLASSES_FAIL: "LOAD_CLASSES_FAIL",

  ADD_CLASSE: "ADD_CLASSE",
  ADD_CLASSE_SUCCESS: "ADD_CLASSE_SUCCESS",
  ADD_CLASSE_FAIL: "ADD_CLASSE_FAIL"
};

module.exports = constants;
